version: '3'

services:
    database:
        container_name: ${DB_NAME}
        image: postgres:14.3
        restart: always
        ports:
            - "${DB_PORT}:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - ./postgres:/var/lib/postgresql/data
        expose:
            - ${DB_PORT}

    app:
        depends_on:
            - database
        container_name: "django-project"
        build:
            context: .
            dockerfile: Dockerfile
        image: carlospaezf/et-group:ninja
        command: python manage.py runserver 0.0.0.0:8000
        restart: always
        ports:
            - "8000:8000"
        environment:
            DB_ENGINE: ${DB_ENGINE}
            DB_NAME: ${DB_NAME}
            DB_PORT: ${DB_PORT}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_HOST: ${DB_HOST}
            SECRET_KEY: ${SECRET_KEY}
            DEBUG: ${DEBUG}
            ALLOWED_HOSTS: ${ALLOWED_HOSTS}
        # command: bin -c "python manage.py runserver"
        # command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py seed product --number=100 && python manage.py runserver"


