GET http://127.0.0.1:8000/api/product/products/
# Authorization: token c7f8d210c68593812c48aaad78199d7530c8cc22

#################################################################

GET http://127.0.0.1:8000/api/product/products/?page=3
# Authorization: token c7f8d210c68593812c48aaad78199d7530c8cc22

#################################################################

GET http://127.0.0.1:8000/api/product/products/top/
Authorization: token c7f8d210c68593812c48aaad78199d7530c8cc22

#################################################################

POST http://127.0.0.1:8000/api/product/products/
Authorization: token c7f8d210c68593812c48aaad78199d7530c8cc22
Content-Type: application/json

{
    "title": "Nuevo producto",
    "price": 12.99,
    "description": "Descripción del nuevo producto",
    "slug": "nuevo-producto",
    "stock": 10,
    "tags": ["Tag 1", "Tag 2"],
    "rating": 3.3
}

#################################################################

GET http://127.0.0.1:8000/api/product/products/1/
Authorization: token c7f8d210c68593812c48aaad78199d7530c8cc22

#################################################################

GET http://127.0.0.1:8000/api/product/products/somebody-national-world-wife-give-hand-perform/
# Authorization: token c7f8d210c68593812c48aaad78199d7530c8cc22

#################################################################

PATCH http://127.0.0.1:8000/api/product/products/1/
Authorization: token c7f8d210c68593812c48aaad78199d7530c8cc22
Content-Type: application/json

{
    "description": "producto actualizado",
    "slug": "corainder_eggs_on_toast"
}

#################################################################

DELETE http://127.0.0.1:8000/api/product/products/1/
Authorization: token c7f8d210c68593812c48aaad78199d7530c8cc22

#################################################################
