POST http://127.0.0.1:8000/api/user/create/
Content-Type: application/json

{
    "email": "test@mail.com",
    "password": "123456",
    "name": "Test User"
}

#############################################################

POST http://127.0.0.1:8000/api/user/token/
Content-Type: application/json

{
    "email": "test@mail.com",
    "password": "123456"
}

#############################################################

GET http://127.0.0.1:8000/api/user/me/
Authorization: token d3cb0507ba05db2416e8a8e07ab1072ab0c56a4d

#############################################################

POST http://127.0.0.1:8000/api/user/token/
Content-Type: application/json

{
    "email": "superuser@email.com",
    "password": "super_password"
}

#############################################################

GET http://127.0.0.1:8000/api/user/me/
Authorization: token 5cba3ae4e8fcb65d4a689700ffd7dbeddccc33f9

#############################################################
