POST http://127.0.0.1:8000/api/user/create/
Content-Type: application/json

{
    "email": "test@mail.com",
    "password": "123456",
    "name": "Test User"
}

#############################################################

POST http://127.0.0.1:8000/api/user/token/
Content-Type: application/json

{
    "email": "test@mail.com",
    "password": "123456"
}

#############################################################

GET http://127.0.0.1:8000/api/user/me/
Authorization: token 794cb2623417c2c6a986100adb4bbf0c9c5d1986
